### ISSUE TITLE
Can You Add How to use this?

### ISSUE THREAD

**Issue by mendelsphotography** [mendelgordon/credit-card-checker#1]
Hi, Can You Add How to use this? Would love to use this for myself and the fact that it has comments is so great. But No Readme File Of how to use it. I know This is Probably For something you are doing But if You Would add A readme File with Info on how to use that would be nice.

**Comment by mendelgordon** [comment]
Added, thanks!

**Comment by mendelsphotography** [comment]
thanks for adding the GUI Also. Also, Link is broken Open a pull request #2  to fix that and some other updates. for markdown code you can learn more [here](https://www.markdownguide.org/basic-syntax/)
